[project]
name = "ev-battery-capacity-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dvc[azure]>=3.67.1",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "mlflow>=3.16.0",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "torch>=2.14.0",
    "tqdm>=4.70.0",
]
